server:
  port: 8091
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://eureka-server-8081:8081/eureka/,http://eureka-server-8082:8082/eureka/,http://eureka-server-8083:8083/eureka/