server:
  port: 8030

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true #忽略微服务的大小写
      routes:
        - id: user-service #路由的id，没有规定规则但要求唯一，建议配合服务名
          uri: lb://user-service #匹配后提供服务的路由地址
          predicates:
            - Method=GET
          filters:
            - PrefixPath=/user #去掉请求前缀
  main:
    web-application-type: reactive
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug # 开启gateway的debug模式