spring:
  application:
    name: eureka-server-8083
server:
  port: 8083
eureka:
  instance:
    hostname: eureka-server-8083
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-8082:8082/eureka/,http://eureka-server-8081:8081/eureka/
  server:
    enable-self-preservation: false